### ISSUE TITLE
.NET Core / .NET Standard Support

### ISSUE THREAD

**Issue by nikeee** [falahati/StartupHelper#1]
Does this library support .NET Core / .NET Standard?

**Comment by falahati** [comment]
It does now. Check the latest release.

But please note that the library is Windows only since it relies on Windows Registry and Windows Task Scheduler. So no mac/linux compatibility.

**Comment by nikeee** [comment]
Thanks!

I'm using it for a .NET Core Winforms Application, so not MacOS or Linux support necessary.
